### ISSUE TITLE
Function calling support

### ISSUE THREAD

**Issue by huytool157** [google/generative-ai-js#14]
I don't see [function calling](https://ai.google.dev/docs/function_calling) support for the Node SDK. Is it coming soon? It's a bit inconvenient to maintain native SDK and raw fetch code at the same time!

**Comment by marb2000** [comment]
Thank you for submitting this feature request! We're definitely interested in supporting Function Calling in the SDK. While we don't have a specific timeline yet, we'll keep you updated on our progress.

**Comment by dannycortesv** [comment]
Looking forward to this feature

**Comment by Neeraj319** [comment]
following

**Comment by chardx** [comment]
following

**Comment by johnomeara1** [comment]
Hey it's been 2 months. No progress....

**Comment by luizguilhermesj** [comment]
+1

**Comment by aroytman** [comment]
+1

FYI, all that it takes to support Function Calling is to allow to specify the API VERSION. Can this be added as a customizable parameter instead of hardcoded in the package?

As a hack, you can currently open the node_modules/@google/generative-ai/dist/index.js file and change the API_VERSION constant on line 156 from "v1" to "v1beta", and Function Calling starts working.

**Comment by hsubox76** [comment]
We've just merged and released both of these things:
https://github.com/google/generative-ai-js/pull/56 - API version switching support
https://github.com/google/generative-ai-js/pull/32 - Basic function calling

Documentation:
See the new `tools` property that can be passed to `getGenerativeModel` through `modelParams`.
https://github.com/google/generative-ai-js/blob/main/docs/reference/generative-ai.modelparams.md

We also are working on automatic function calling in `ChatSession` and hope to have that out soon.
