### ISSUE TITLE
Setting API Key as Environment Variable in Google Generative AI Sample for Web on a Live HTTP Server

### ISSUE THREAD

**Issue by TSSFL** [google/generative-ai-js#42]
Not really, an issue, but a help request!

I used the Google Generative AI Sample for Web https://github.com/google/generative-ai-js/tree/main/samples/web on a live HTTP server. I placed the application at https://www.example.com/genai, where genai is the folder for the app, and now I need assistance in setting the API Key as an environment variable according to the instructions provided, see https://github.com/google/generative-ai-js/blob/main/samples/web/http-server.js ?  Please note that I do not have root access.

However, any help to transform how the API Key is accessed just like it is done for ChatGPT https://niek.github.io/chatgpt-web? I mean to make it possible to just copy and paste the key on the web interface rather than storing it in the back-end?

**Comment by hsubox76** [comment]
It's up to you how you want to store the API key, there's no requirement from this SDK that it be an environment variable. You just need to pass it as a string when you instantiate `GoogleGenerativeAI`, like:

```
const genAI = new GoogleGenerativeAI("your-api-key");
```

Since that's the entry point to this SDK, I think it's out of scope for this repo to determine where that string comes from. If you don't have access to env variables, you can hardcode it, you can type it in to a browser form, whatever you like. Where you put and get your API key is a broader question that applies to any web app using an API, so I think you should be able to find a lot of material out there.

Specifically if you're trying to modify the sample app, just hardcode your key (or however you want to get the string) in this line: https://github.com/google/generative-ai-js/blob/d9c3f4d421100b5656d63e084ca93e418d00bf07/samples/web/utils/shared.js#L32 and get rid of line 30 as well as all the lines in http-server.js that refer to the API_KEY.

**Comment by sofiqulislams** [comment]
GEMINI_API_KEY=your_key_here
